name: pull draft from hatenablog

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Draft Entry Title"
        required: true

jobs:
  pull-draft:
    uses: hatena/hatenablog-workflows/.github/workflows/pull-draft.yaml@8564b85b51cda20eb962f0dec3bf3fcff3dd0326 # v2.0.7
    with:
      title: ${{ github.event.inputs.title }}
      draft: true
      BLOG_DOMAIN: ${{ vars.BLOG_DOMAIN }}
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
